//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.11 at 11:22:16 PM CET 
//


package com.toupclouders.chesscloud.base;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.toupclouders.chesscloud.constant.Day;


/**
 * <p>Java class for ExtendedPgnSearchRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedPgnSearchRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.toupclouders.com/chesscloud/base}PgnSearchRequest">
 *       &lt;sequence>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Zipcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Day" type="{http://www.toupclouders.com/chesscloud/constant}Day"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedPgnSearchRequest", propOrder = {
    "state",
    "zipcode",
    "day"
})
public class ExtendedPgnSearchRequest
    extends PgnSearchRequest
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "Zipcode", required = true)
    protected String zipcode;
    @XmlElement(name = "Day", required = true)
    protected Day day;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the zipcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * Sets the value of the zipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipcode(String value) {
        this.zipcode = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link Day }
     *     
     */
    public Day getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link Day }
     *     
     */
    public void setDay(Day value) {
        this.day = value;
    }

    public ExtendedPgnSearchRequest withState(String value) {
        setState(value);
        return this;
    }

    public ExtendedPgnSearchRequest withZipcode(String value) {
        setZipcode(value);
        return this;
    }

    public ExtendedPgnSearchRequest withDay(Day value) {
        setDay(value);
        return this;
    }

    @Override
    public ExtendedPgnSearchRequest withTest(Calendar... values) {
        if (values!= null) {
            for (Calendar value: values) {
                getTest().add(value);
            }
        }
        return this;
    }

    @Override
    public ExtendedPgnSearchRequest withTest(Collection<Calendar> values) {
        if (values!= null) {
            getTest().addAll(values);
        }
        return this;
    }

}
