//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.11 at 11:22:16 PM CET 
//


package com.toupclouders.chesscloud.base;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.toupclouders.chesscloud.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.toupclouders.chesscloud.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DateRange }
     * 
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link PgnInfo }
     * 
     */
    public PgnInfo createPgnInfo() {
        return new PgnInfo();
    }

    /**
     * Create an instance of {@link ExtendedPgnSearchRequest }
     * 
     */
    public ExtendedPgnSearchRequest createExtendedPgnSearchRequest() {
        return new ExtendedPgnSearchRequest();
    }

    /**
     * Create an instance of {@link GetPgnReply }
     * 
     */
    public GetPgnReply createGetPgnReply() {
        return new GetPgnReply();
    }

    /**
     * Create an instance of {@link GetPgnRequest }
     * 
     */
    public GetPgnRequest createGetPgnRequest() {
        return new GetPgnRequest();
    }

    /**
     * Create an instance of {@link PgnSearchRequest }
     * 
     */
    public PgnSearchRequest createPgnSearchRequest() {
        return new PgnSearchRequest();
    }

}
