//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.11 at 11:22:16 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.toupclouders.com/chesscloud/base")
package com.toupclouders.chesscloud.base;
