//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.11 at 11:22:16 PM CET 
//


package com.toupclouders.chesscloud.base;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.topclouders.chesscloud.BaseBean;


/**
 * <p>Java class for PgnInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PgnInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="white" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="whiteElo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="black" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blackElo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PgnInfo", propOrder = {
    "white",
    "whiteElo",
    "black",
    "blackElo"
})
public class PgnInfo
    extends BaseBean
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String white;
    protected String whiteElo;
    @XmlElement(required = true)
    protected String black;
    protected String blackElo;

    /**
     * Gets the value of the white property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhite() {
        return white;
    }

    /**
     * Sets the value of the white property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhite(String value) {
        this.white = value;
    }

    /**
     * Gets the value of the whiteElo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhiteElo() {
        return whiteElo;
    }

    /**
     * Sets the value of the whiteElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhiteElo(String value) {
        this.whiteElo = value;
    }

    /**
     * Gets the value of the black property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlack() {
        return black;
    }

    /**
     * Sets the value of the black property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlack(String value) {
        this.black = value;
    }

    /**
     * Gets the value of the blackElo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlackElo() {
        return blackElo;
    }

    /**
     * Sets the value of the blackElo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlackElo(String value) {
        this.blackElo = value;
    }

    public PgnInfo withWhite(String value) {
        setWhite(value);
        return this;
    }

    public PgnInfo withWhiteElo(String value) {
        setWhiteElo(value);
        return this;
    }

    public PgnInfo withBlack(String value) {
        setBlack(value);
        return this;
    }

    public PgnInfo withBlackElo(String value) {
        setBlackElo(value);
        return this;
    }

}
